services:
  norber_api_php:
    container_name: norber_api_php
    build:
      context: "./.docker"
      dockerfile: Dockerfile
    ports:
      - "9001:9000" # fpm
      - "5173:5173" # vite
    volumes:
      - "./.:/var/www/html"
